name: Development Pipeline

run-name: Development to ${{ github.event.pull_request.title }} by ${{ github.actor }}

on:
  push:
    branches: ["develop", "main", "test"]
  pull_request:
    branches: ["develop", "main", test]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  call-linter:
    uses: ./.github/workflows/linter.yml
  call-build:
    needs: call-linter
    uses: ./.github/workflows/build.yml
